version: "3.4"
services:
  cardano:
    image: cardanosolutions/cardano-node-ogmios:latest
    volumes:
      - cardano-db:/db
    labels:
      - traefik.enable=true
      - traefik.http.routers.cardano.service=cardano
      - traefik.http.routers.cardano.entrypoints=websecure
      - traefik.http.routers.cardano.rule=Host(`${EC_HOST}.${DOMAIN}`)
      - traefik.http.routers.cardano.tls.certresolver=letsencrypt
      - traefik.http.routers.cardanolb.service=cardano
      - traefik.http.routers.cardanolb.entrypoints=websecure
      - traefik.http.routers.cardanolb.rule=Host(`${EC_LB}.${DOMAIN}`)
      - traefik.http.routers.cardanolb.tls.certresolver=letsencrypt
      - traefik.http.services.cardano.loadbalancer.server.port=1337

volumes:
  cardano-db:
