x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION}
    restart: "unless-stopped"
    command:
      - run
      - --topology /config/topology.json
      - --database-path /data/db
      - --socket-path /ipc/node.socket
      - --host-addr 0.0.0.0
      - --port ${RPC_PORT}
      - --config /config/config.json
    environment:
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/config/${NETWORK}:/config
      - node-db:/data/db
      - node-ipc:/ipc
    labels:
      - metrics.scrape=true
      - metrics.port=12798
      - metrics.path=/metrics
      - metrics.network=cardano-node-${NETWORK}
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST}.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}.rule=Host(`${RPC_HOST}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST}lb.service=${RPC_HOST}
      - traefik.http.routers.${RPC_HOST}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST}lb.rule=Host(`${RPC_LB}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST}.loadbalancer.server.port=${RPC_PORT}
    <<: *logging

volumes:
  node-db:
  node-ipc:
